routes/web.php
    Route::get('candidates/import-2','CandidatesController@importFields')->name('candidates.import-2');
    Route::post('candidates/import-2','CandidatesController@saveImportFields')->name('candidates.import-save-fields');
    Route::get('candidates/import-3','CandidatesController@importPreview')->name('candidates.import-preview');
    Route::post('candidates/process-import','CandidatesController@processImport')->name('candidates.import-process');
    Route::get('candidates/import-4','CandidatesController@completeImport')->name('candidates.import-complete');
    Route::get('candidates/test-results/{user}','CandidatesController@tests')->name('candidates.tests');
    Route::resource('candidates', 'CandidatesController');
    Route::resource('categories', 'CategoriesController');

    Route::resource('notes','NotesController');
    Route::get('user-notes/{user}','NotesController@index')->name('notes.index');
    Route::get('user-notes/create/{user}','NotesController@create')->name('notes.create');
    Route::post('user-notes/{user}','NotesController@store')->name('notes.store');

    Route::resource('attachments', 'AttachmentsController');
    Route::get('user-attachments/{user}','AttachmentsController@index')->name('attachments.index');
    Route::get('user-attachments/create/{user}','AttachmentsController@create')->name('attachments.create');
    Route::post('user-attachments/{user}','AttachmentsController@store')->name('attachments.store');

    Route::get('employer-remove-file/{fieldId}/{userId}','EmployersController@removeFile')->name('employer.remove-file');
    Route::get('employers/search','EmployersController@search')->name('employers.search');
    Route::get('employers/export','EmployersController@export')->name('employers.export');
    Route::get('employers/import-1','EmployersController@importForm')->name('employers.import-1');
    Route::post('employers/import-1','EmployersController@importUpload')->name('employers.import-upload');
    Route::get('employers/import-2','EmployersController@importFields')->name('employers.import-2');
    Route::post('employers/import-2','EmployersController@saveImportFields')->name('employers.import-save-fields');
    Route::get('employers/import-3','EmployersController@importPreview')->name('employers.import-preview');
    Route::post('employers/process-import','EmployersController@processImport')->name('employers.import-process');
    Route::get('employers/import-4','EmployersController@completeImport')->name('employers.import-complete');
    Route::resource('employers', 'EmployersController');

    Route::resource('employments', 'EmploymentsController');
    Route::get('employment-records/{user}','EmploymentsController@index')->name('employments.index');
    Route::get('employment-records/create/{user}','EmploymentsController@create')->name('employments.create');
    Route::post('employment-records/{user}','EmploymentsController@store')->name('employments.store');
    Route::get('browse-employments','EmploymentsController@browse')->name('employments.browse');

    Route::get('create-employment','EmploymentsController@createEmployment')->name('employments.create-employment');
    Route::post('store-employment','EmploymentsController@storeEmployment')->name('employments.store-employment');

    Route::resource('employment-comments', 'EmploymentCommentsController');
    Route::get('employment-comment/{employment}','EmploymentCommentsController@index')->name('employment-comments.index');
    Route::get('employment-comment/create/{employment}','EmploymentCommentsController@create')->name('employment-comments.create');
    Route::post('employment-comment/{employment}','EmploymentCommentsController@store')->name('employment-comments.store');

    Route::post('employment-comment/upload-attachment/{id}','EmploymentCommentsController@upload')->name('employment-comments.upload');
    Route::post('employment-comment/remove-upload/{id}','EmploymentCommentsController@removeUpload')->name('employment-comments.remove-upload');
    Route::get('employment-comment/download-attachment/{employmentCommentAttachment}','EmploymentCommentsController@downloadAttachment')->name('employment-comments.download-attachment');
    Route::get('employment-comment/download-attachments/{employmentComment}','EmploymentCommentsController@downloadAttachments')->name('employment-comments.download-attachments');

    Route::get('employment-comment/delete-attachment/{employmentCommentAttachment}','EmploymentCommentsController@deleteAttachment')->name('employment-comments.delete-attachment');


    Route::resource('orders', 'OrdersController');
    Route::post('create-order','OrdersController@doCreate')->name('orders.do-create');
    Route::get('orders/create/{orderForm}','OrdersController@create')->name('orders.create');
    Route::post('orders/create/{orderForm}','OrdersController@store')->name('orders.store');
    Route::get('order-remove-file/{fieldId}/{orderId}','OrdersController@removeFile')->name('order.remove-file');
    Route::post('order-create-invoice/{order}','OrdersController@createOrderInvoice')->name('order.create-invoice');

    Route::resource('order-comments', 'OrderCommentsController');
    Route::get('order-comment/{order}','OrderCommentsController@index')->name('order-comments.index');
    Route::get('order-comment/create/{order}','OrderCommentsController@create')->name('order-comments.create');
    Route::post('order-comment/{order}','OrderCommentsController@store')->name('order-comments.store');

    Route::post('order-comment/upload-attachment/{id}','OrderCommentsController@upload')->name('order-comments.upload');
    Route::post('order-comment/remove-upload/{id}','OrderCommentsController@removeUpload')->name('order-comments.remove-upload');
    Route::get('order-comment/download-attachment/{orderCommentAttachment}','OrderCommentsController@downloadAttachment')->name('order-comments.download-attachment');
    Route::get('order-comment/download-attachments/{orderComment}','OrderCommentsController@downloadAttachments')->name('order-comments.download-attachments');

    Route::get('order-comment/delete-attachment/{orderCommentAttachment}','OrderCommentsController@deleteAttachment')->name('order-comments.delete-attachment');

    //vacancy routes
    Route::resource('job-categories', 'JobCategoriesController');
    Route::resource('vacancies', 'VacanciesController');

    Route::resource('applications', 'ApplicationsController');
    Route::get('application-records/{vacancy}','ApplicationsController@index')->name('applications.index');
    Route::get('shortlist-application/{application}','ApplicationsController@shortlist')->name('applications.shortlist');

    Route::resource('emails', 'EmailsController');
    Route::resource('email-resources', 'EmailResourcesController');
    Route::get('email/download-attachment/{emailAttachment}','EmailsController@downloadAttachment')->name('emails.download-attachment');
    Route::get('email/download-attachments/{email}','EmailsController@downloadAttachments')->name('emails.download-attachments');
    Route::get('email/delete-attachment/{emailAttachment}','EmailsController@deleteAttachment')->name('emails.delete-attachment');
    Route::get('email/send-now/{email}','EmailsController@sendNow')->name('emails.send-now');
    Route::post('emails/delete-multiple','EmailsController@deleteMultiple')->name('email.delete-multiple');
    Route::get('email/delete/{id}','EmailsController@destroy')->name('email.delete');

    Route::resource('email-templates', 'EmailTemplatesController');
    Route::get('get-email-template/{emailTemplate}','EmailTemplatesController@getTemplate')->name('email-templates.get');


    Route::resource('sms', 'SmsController');
    Route::get('sms-msg/send-now/{sms}','SmsController@sendNow')->name('sms.send-now');
    Route::post('sms-msg/delete-multiple','SmsController@deleteMultiple')->name('sms.delete-multiple');
    Route::get('sms-msg/delete/{id}','SmsController@destroy')->name('sms.delete');
    Route::resource('sms-templates', 'SmsTemplatesController');
    Route::get('get-sms-template/{smsTemplate}','SmsTemplatesController@getTemplate')->name('sms-templates.get');

    Route::resource('interviews', 'InterviewsController');

    Route::resource('tests', 'TestsController');
    Route::resource('test-questions', 'TestQuestionsController');
    Route::get('test-question/{test}','TestQuestionsController@index')->name('test-questions.index');
    Route::get('test-question/create/{test}','TestQuestionsController@create')->name('test-questions.create');
    Route::post('test-question/{test}','TestQuestionsController@store')->name('test-questions.store');
    Route::post('test-option/store/{testQuestion}','TestQuestionsController@storeOptions')->name('test-options.store');
    Route::get('test-options/edit/{testOption}','TestQuestionsController@editOption')->name('test-options.edit');
    Route::post('test-options/update/{testOption}','TestQuestionsController@updateOption')->name('test-options.update');
    Route::get('test-options/delete/{testOption}','TestQuestionsController@deleteOption')->name('test-options.delete');
    Route::get('test-attempts/{test}','TestsController@attempts')->name('tests.attempts');
    Route::get('delete-result/{userTest}','TestsController@deleteResult')->name('tests.delete-result');
    Route::get('view-result/{userTest}','TestsController@results')->name('tests.results');

    //This group uses middleware to apply the access gate to settings related routes
    Route::group(['middleware'=>['admin-settings']],function(){

        Route::resource('api-tokens', 'ApiTokensController');

        Route::get('settings/{group}','SettingsController@settings')->name('settings');
        Route::post('save-settings','SettingsController@saveSettings')->name('save-settings');
        Route::get('settings/remove-picture/{setting}','SettingsController@removePicture')->name('remove-picture');

app/EmploymentComment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmploymentComment extends Model
{
    protected $fillable = ['employment_id','user_id','content'];

    protected $touches = ['employment'];

    public function employment(){
        return $this->belongsTo(Employment::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function employmentCommentAttachments(){
        return $this->hasMany(EmploymentCommentAttachment::class);
    }

}

Resources/views/admin/employment-comments/create.blade.php
@extends('layouts.admin-page')

@section('pageTitle',__('site.create-new').' '.__('site.employment-comment'))
@section('page-title',$employment->employer->user->name.'('.__('site.employer').') - '.$employment->candidate->user->name.'('.__('site.candidate').')')

@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div  >
                    <div >
                        <a href="{{ route('admin.employment-comments.index',['employment'=>$employment->id]) }}" title="@lang('site.back')"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                        <br />
                        <br />


                        <form method="POST" action="{{ route('admin.employment-comments.store',['employment'=>$employment->id]) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('admin.employment-comments.form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@include('admin.employment-comments.form-include')

Resources/views/admin/employment-comments/edit.blade.php
@extends('layouts.admin-page')

@section('pageTitle',__('site.edit').' '.__('site.comment'))
@section('page-title',$employmentcomment->employment->employer->user->name.'('.__('site.employer').') - '.$employmentcomment->employment->candidate->user->name.'('.__('site.candidate').')'.' - '.\Illuminate\Support\Carbon::parse($employmentcomment->created_at)->diffForHumans())


@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div  >
                    <div  >
                        <a href="{{ route('admin.employment-comments.index',['employment'=>$employmentcomment->employment->id]) }}" title="@lang('site.back')"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                        <br />
                        <br />



                        <form method="POST" action="{{ url('/admin/employment-comments/' . $employmentcomment->id) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('admin.employment-comments.form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@include('admin.employment-comments.form-include')

Resources/views/admin/employment-comments/form-include.blade.php
@section('footer')
    <script src="{{ asset('vendor/summernote/summernote-bs4.min.js') }}"></script>

    <!-- dropzone JS
		============================================ -->
    <script src="{{ asset('vendor/dropzone/dropzone.js') }}"></script>
    <script src="{{ asset('js/admin/ofg-edit.js') }}"></script>
    <script>
"use strict";

        Dropzone.autoDiscover = false;
        jQuery(document).ready(function() {

            $("div#my-dropzone").dropzone({
                url: "{{ route('admin.employment-comments.upload',['id'=>$msgId]) }}",
                acceptedFiles: ".jpeg,.jpg,.png,.gif,.pdf,.doc,.docx,.ppt,.pptx,.zip,.mp3,.mp4",
                maxFilesize: 20, // MB
                success: function (file, response) {
                    console.log("Sucesso");
                    console.log(response);
                },
                headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') },
                addRemoveLinks: true,
                removedfile: function(file) {
                    var name = file.name;
                    console.log(name);

                    $.ajax({
                        type: 'POST',
                        url: '{{ route('admin.employment-comments.remove-upload',['id'=>$msgId]) }}',
                        data: {name: name,request: 2, _token:'{{ csrf_token() }}'},
                        sucess: function(data){
                            console.log('success: ' + data);
                        }
                    });
                    var _ref;
                    return (_ref = file.previewElement) != null? _ref.parentNode.removeChild(file.previewElement) : void 0;
                },
                dictRemoveFile: '@lang('site.remove-file')',
                dictCancelUpload: '@lang('site.cancel-upload')',
                dictCancelUploadConfirmation: '@lang('site.cancel-confirm')'
            });

        });

    </script>
@endsection


@section('header')
    <link rel="stylesheet" href="{{ asset('vendor/summernote/summernote-bs4.css') }}">
    <link rel="stylesheet" href="{{ asset('vendor/dropzone/dropzone.css') }}">

@endsection

Resources/views/admin/employment-comments/form.blade.php
<div class="form-group {{ $errors->has('content') ? 'has-error' : ''}}">
    <label for="content" class="control-label">@lang('site.content')</label>
    <textarea class="form-control" rows="5" name="content" type="textarea" id="content" >{{ old('content',isset($employmentcomment->content) ? $employmentcomment->content : '') }}</textarea>
    {!! clean( $errors->first('content', '<p class="help-block">:message</p>') ) !!}
</div>

@if($formMode=='create')
    <div class="row">
        <div class="col-md-6">
            <div class="form-check">
                <input class="form-check-input" checked  type="checkbox" value="1" id="notify" name="notify">
                <label class="form-check-label" for="notify">
                    @lang('site.notify-employer')
                </label>
            </div>
        </div>
    </div>
@endif

@if($formMode=='edit' && $employmentcomment->employmentCommentAttachments()->count() > 0)
    <div  class="int_tpmb">
        <p  >
            <span><i class="fa fa-paperclip"></i> {{ $employmentcomment->employmentCommentAttachments()->count() }} @if($employmentcomment->employmentCommentAttachments()->count()>1) @lang('site.attachments') @else @lang('site.attachment') @endif - </span>
            <a href="{{ route('admin.employment-comments.download-attachments',['employmentComment'=>$employmentcomment->id]) }}" class="btn btn-default btn-xs">@lang('site.download-all') <i class="fa fa-file-zip-o"></i> </a>
        </p>

        <div>
            <div class="row" >
                @foreach($employmentcomment->employmentCommentAttachments as $attachment)
                      <div    class="col-md-4 int_mth"  >
                            <a href="{{ route('admin.employment-comments.download-attachment',['employmentCommentAttachment'=>$attachment->id]) }}">

                            <div class="card"  >


                                @if(isImage($attachment->file_path))
                                    <img  src="{{ route('admin.image') }}?file={{ $attachment->file_path }}"  class="card-img-top int_mh270" alt=""/>
                                 @endif

                                <div class="card-body int_txcen"   >
                                    @if(!isImage($attachment->file_path))
                                        <i class="int_fs200 fa fa-file text-info"></i>
                                    @endif
                                </div>
                                <div class="card-footer">
                                    {{ $attachment->file_name }}
                                </div>


                            </div>
                            </a>
                          <a  onclick="return confirm(&quot;@lang('site.confirm-delete')&quot;)"  class="int_mt10 btn btn-danger btn-block btn-sm" href="{{ route('admin.employment-comments.delete-attachment',['employmentCommentAttachment'=>$attachment->id]) }}"><i class="fa fa-trash"></i> @lang('site.delete')</a>
                        </div>

                @endforeach


            </div>

        </div>
    </div>
@endif
<div id="dropzone" class="dropmail int_tpmb" >

    <div class="dropzone dropzone-custom needsclick" id="my-dropzone">
        <div class="dz-message needsclick download-custom">
            <i class="fa fa-download" aria-hidden="true"></i>
            <h1>@lang('site.attachments')</h1>
            <h2>@lang('site.upload-info')</h2>

        </div>
    </div>


</div>
<input type="hidden" name="msg_id" value="{{ $msgId }}"/>

<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? __('site.update') : __('site.create') }}">
</div>

Resources/views/admin/employment-comments/index.blade.php
@extends('layouts.admin-page-wide')

@section('search-form',route('admin.employment-comments.index',['employment'=>$employment->id]))

@section('pageTitle',__('site.employment-comments'))
@section('page-title',$employment->employer->user->name.'('.__('site.employer').') - '.$employment->candidate->user->name.'('.__('site.candidate').')')

@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div >
                    <div  >
                        @can('access','view_employments')
                        <a href="{{ route('admin.employments.index',['user'=>$employment->employer->user_id]) }}" title="@lang('site.back')"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                        @endcan

                        @can('access','create_employment_comment')
                        <a href="{{ route('admin.employment-comments.create',['employment'=>$employment->id]) }}" class="btn btn-success btn-sm" title="@lang('site.add-new')">
                            <i class="fa fa-plus" aria-hidden="true"></i> @lang('site.add-new')
                        </a>
                        @endcan



                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>@lang('site.created-by')</th>
                                        <th>@lang('site.added-on')</th>
                                        <th>@lang('site.content')</th><th>@lang('site.actions')</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($employmentcomments as $item)
                                    <tr>
                                        <td>{{ $loop->iteration + ( (Request::get('page',1)-1) *$perPage) }}</td>
                                        <td>{{ $item->user->name }} ({{ roleName($item->user->role_id) }})</td>
                                        <td>{{ \Illuminate\Support\Carbon::parse($item->created_at)->format('d/M/Y') }}</td>
                                        <td>{{ limitLength(strip_tags($item->content),80) }}
                                        @if($item->employmentCommentAttachments()->count()>0)
                                            <i class="fa fa-paperclip"></i>
                                            @endif
                                        </td>
                                        <td>

                                            <div class="btn-group dropup">
                                                <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="ni ni-settings"></i> @lang('site.actions')
                                                </button>
                                                <div class="dropdown-menu">
                                                    <!-- Dropdown menu links -->
                                                    @can('access','view_employment_comment')
                                                    <a class="dropdown-item" href="{{ url('/admin/employment-comments/' . $item->id) }}">@lang('site.view')</a>
                                                    @endcan

                                                    @can('access','edit_employment_comment')
                                                    <a class="dropdown-item" href="{{ url('/admin/employment-comments/' . $item->id . '/edit') }}">@lang('site.edit')</a>
                                                    @endcan

                                                    @can('access','delete_employment_comment')
                                                    <a class="dropdown-item" href="#" onclick="$('#deleteForm{{ $item->id }}').submit()">@lang('site.delete')</a>
                                                    @endcan



                                                </div>
                                            </div>
                                            <form  onsubmit="return confirm(&quot;@lang('site.confirm-delete')&quot;)"   id="deleteForm{{ $item->id }}"  method="POST" action="{{ url('/admin/employment-comments' . '/' . $item->id) }}" accept-charset="UTF-8" class="int_inlinedisp">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                            </form>


                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! clean( $employmentcomments->appends(request()->input())->render() ) !!} </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

Resources/views/admin/employment-comments/show.blade.php
@extends('layouts.admin-page')

@section('pageTitle',__('site.employment-comment'))
 @section('page-title',$employmentcomment->employment->employer->user->name.'('.__('site.employer').') - '.$employmentcomment->employment->candidate->user->name.'('.__('site.candidate').')')
@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div  >
                    <div  >
                        @can('access','view_employment_comments')
                        <a href="{{ route('admin.employment-comments.index',['employment'=>$employmentcomment->employment_id]) }}"  ><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                        @endcan

                        @can('access','edit_employment_comment')
                        <a href="{{ url('/admin/employment-comments/' . $employmentcomment->id . '/edit') }}" ><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> @lang('site.edit')</button></a>
                        @endcan

                        @can('access','delete_employment_comment')
                        <form method="POST" action="{{ url('admin/employment-comments' . '/' . $employmentcomment->id) }}" accept-charset="UTF-8" class="int_inlinedisp">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-sm" title="@lang('site.delete')" onclick="return confirm(&quot;@lang('site.confirm-delete')?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> @lang('site.delete')</button>
                        </form>
                        @endcan

                        <br/>
                        <br/>

                        <div >
                            <table class="table">
                                <tbody>
                                <tr><th> @lang('site.created-by') </th><td>
                                        {{ $employmentcomment->user->name }} ({{ roleName($employmentcomment->user->role_id) }})
                                    </td></tr>
                                    <tr><th> @lang('site.added-on') </th><td>

                                            {{ \Illuminate\Support\Carbon::parse($employmentcomment->created_at)->format('d/M/Y') }}
                                        </td></tr>
                                </tbody>
                            </table>

                            <div class="card int_twmb20" >
                                <div class="card-body">
                                    {!! clean( check($employmentcomment->content) ) !!}
                                </div>

                            </div>

                            @if( $employmentcomment->employmentCommentAttachments()->count() > 0)
                                <div  class="int_tpmb">
                                    <p  >
                                        <span><i class="fa fa-paperclip"></i> {{ $employmentcomment->employmentCommentAttachments()->count() }} @if($employmentcomment->employmentCommentAttachments()->count()>1) @lang('site.attachments') @else @lang('site.attachment') @endif - </span>
                                        <a href="{{ route('admin.employment-comments.download-attachments',['employmentComment'=>$employmentcomment->id]) }}" class="btn btn-default btn-xs">@lang('site.download-all') <i class="fa fa-file-zip-o"></i> </a>
                                    </p>

                                    <div>
                                        <div class="row" >
                                            @foreach($employmentcomment->employmentCommentAttachments as $attachment)
                                                <div class="col-md-4 int_mbh"   >
                                                    <a href="{{ route('admin.employment-comments.download-attachment',['employmentCommentAttachment'=>$attachment->id]) }}">

                                                        <div class="card"  >


                                                            @if(isImage($attachment->file_path))
                                                                <img  src="{{ route('admin.image') }}?file={{ $attachment->file_path }}"  class="card-img-top int_mh270" alt=""/>
                                                            @endif

                                                            <div class="card-body int_txcen"   >
                                                                @if(!isImage($attachment->file_path))
                                                                    <i class="int_fs200 fa fa-file text-info"></i>
                                                                @endif
                                                            </div>
                                                            <div class="card-footer">
                                                                {{ $attachment->file_name }}
                                                            </div>


                                                        </div>
                                                    </a>
                                                </div>

                                            @endforeach


                                        </div>

                                    </div>
                                </div>
                            @endif
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection