routes/web.php
        Route::post('save-sms-setting','SmsGatewaysController@saveSmsSetting')->name('save-sms-setting');
        Route::get('sms-gateway/{smsGateway}','SmsGatewaysController@smsFields')->name('edit-sms-gateway');
        Route::post('save-sms-gateway/{smsGateway}','SmsGatewaysController@saveField')->name('save-sms-gateway');
        Route::get('gateway-status/{smsGateway}/{status}','SmsGatewaysController@setSmsStatus')->name('sms-status');
        Route::get('gateway-install/{gateway}','SmsGatewaysController@install')->name('sms-install');

        //routes for templates
        Route::get('templates','TemplatesController@index')->name('templates');
        Route::get('templates/install/{templateDir}','TemplatesController@install')->name('templates.install');
        Route::get('templates/settings','TemplatesController@settings')->name('templates.settings');
        Route::get('templates/colors','TemplatesController@colors')->name('templates.colors');
        Route::post('templates/save-options/{option}','TemplatesController@saveOptions')->name('templates.save-options');
        Route::post('templates/upload','TemplatesController@upload')->name('templates.upload');
        Route::post('templates/save-colors','TemplatesController@saveColors')->name('templates.save-colors');

        Route::get('menus/header','MenuController@headerMenu')->name('menus.header');
        Route::get('menus/footer','MenuController@footerMenu')->name('menus.footer');
        Route::get('menus/load-header','MenuController@loadHeaderMenu')->name('menus.load-header');
        Route::post('menus/save-header','MenuController@saveHeaderMenu')->name('menus.save-header');
        Route::post('menus/update-header/{headerMenu}','MenuController@updateHeaderMenu')->name('menus.update-header');
        Route::get('menus/delete-header/{headerMenu}','MenuController@deleteHeaderMenu')->name('menus.delete-header');

        Route::get('menus/load-footer','MenuController@loadFooterMenu')->name('menus.load-footer');
        Route::post('menus/save-footer','MenuController@saveFooterMenu')->name('menus.save-footer');
        Route::post('menus/update-footer/{footerMenu}','MenuController@updateFooterMenu')->name('menus.update-footer');
        Route::get('menus/delete-footer/{footerMenu}','MenuController@deleteFooterMenu')->name('menus.delete-footer');

        Route::resource('order-forms', 'OrderFormsController');

        Route::resource('order-field-groups', 'OrderFieldGroupsController');

        Route::get('order-form/field-groups/{orderForm}','OrderFieldGroupsController@index')->name('order-field-groups.index');
        Route::get('order-form/field-groups/create/{orderForm}','OrderFieldGroupsController@create')->name('order-field-groups.create');
        Route::post('order-form/field-groups/{orderForm}','OrderFieldGroupsController@store')->name('order-field-groups.store');


        Route::resource('order-fields', 'OrderFieldsController');
        Route::get('order-form/fields/{orderFieldGroup}','OrderFieldsController@index')->name('order-fields.index');
        Route::get('order-form/create/{orderFieldGroup}','OrderFieldsController@create')->name('order-fields.create');
        Route::post('order-form/{orderFieldGroup}','OrderFieldsController@store')->name('order-fields.store');

        Route::resource('employer-field-groups', 'EmployerFieldGroupsController');

        Route::resource('employer-fields', 'EmployerFieldsController');
        Route::get('employer-form/fields/{employerFieldGroup}','EmployerFieldsController@index')->name('employer-fields.index');
        Route::get('employer-form/create/{employerFieldGroup}','EmployerFieldsController@create')->name('employer-fields.create');
        Route::post('employer-form/{employerFieldGroup}','EmployerFieldsController@store')->name('employer-fields.store');


        Route::resource('candidate-field-groups', 'CandidateFieldGroupsController');
        Route::resource('candidate-fields', 'CandidateFieldsController');
        Route::get('candidate-form/fields/{candidateFieldGroup}','CandidateFieldsController@index')->name('candidate-fields.index');
        Route::get('candidate-form/create/{candidateFieldGroup}','CandidateFieldsController@create')->name('candidate-fields.create');
        Route::post('candidate-form/{candidateFieldGroup}','CandidateFieldsController@store')->name('candidate-fields.store');

        Route::resource('roles', 'RolesController');

    });

    Route::get('profile','SettingsController@profile')->name('profile');
    Route::post('profile','SettingsController@saveProfile')->name('save-profile');

    Route::get('frontend','SettingsController@frontend')->name('frontend');
    Route::post('frontend','SettingsController@saveFrontend')->name('save-frontend');

    //contract routes
    Route::resource('contracts', 'ContractsController');
    Route::get('contracts/get-template/{contractTemplate}','ContractsController@getTemplate')->name('contracts.get-template');
    Route::get('contracts/send/{contract}','ContractsController@sendContract')->name('contracts.send');
    Route::get('contracts/download/{contract}','ContractsController@download')->name('contracts.download');
    Route::resource('contract-templates', 'ContractTemplatesController');

});

Route::group(['middleware'=>['auth','admin'],'prefix' => 'admin', 'as' => 'admin.','namespace'=>'Admin'],function() {

    Route::get('users','UsersController@index')->name('users.index');
    Route::get('users/delete/{user}','UsersController@destroy')->name('users.delete');


});

Route::group(['middleware'=>['employer'],'prefix' => 'employer', 'as' => 'employer.','namespace'=>'Employer'],function() {

    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::get('orders','OrderController@orders')->name('orders');
    Route::get('orders/{order}','OrderController@view')->name('view-order');
    Route::get('order-comments/{order}','OrderController@comments')->name('orders.comments');
    Route::post('order-comments/{order}','OrderController@addComment')->name('orders.add-comment');
    Route::get('order-comment/download-attachment/{orderCommentAttachment}','OrderController@downloadAttachment')->name('order-comments.download-attachment');
    Route::get('order-comment/download-attachments/{orderComment}','OrderController@downloadAttachments')->name('order-comments.download-attachments');

    Route::get('placements','PlacementController@placements')->name('placements');
    Route::get('placements/{employment}','PlacementController@view')->name('view-placement');
    Route::get('placement-comments/{employment}','PlacementController@comments')->name('placements.comments');
    Route::post('placement-comments/{employment}','PlacementController@addComment')->name('placements.add-comment');
    Route::get('placement-comment/download-attachment/{employmentCommentAttachment}','PlacementController@downloadAttachment')->name('placement-comments.download-attachment');
    Route::get('placement-comment/download-attachments/{employmentComment}','PlacementController@downloadAttachments')->name('placement-comments.download-attachments');
    Route::post('placement-comment/upload/{id}','PlacementController@upload')->name('placement-comments.upload');
    Route::post('placement-comment/remove-upload/{id}','PlacementController@removeUpload')->name('placement-comments.remove-upload');

    Route::get('interviews','InterviewController@interviews')->name('interviews');
    Route::get('interviews/{interview}','InterviewController@view')->name('view-interview');
    Route::post('interviews/{interview}','InterviewController@update')->name('update-interview');

    Route::get('image','HomeController@showImage')->name('image');
    Route::get('download','HomeController@download')->name('download');
    Route::get('employer-remove-file/{fieldId}/{userId}','HomeController@removeFile')->name('remove-file');

    Route::get('profile','ProfileController@profile')->name('profile');
    Route::post('update-profile','ProfileController@update')->name('save-profile');

});

Route::group(['middleware'=>['candidate'],'prefix' => 'candidate', 'as' => 'candidate.','namespace'=>'Candidate'],function() {

    Route::get('dashboard', 'HomeController@index')->name('dashboard');
    Route::get('/vacancy-application/{vacancy}','VacanciesController@apply')->name('vacancy.apply');
    Route::post('/vacancy-application/{vacancy}','VacanciesController@submit')->name('vacancy.submit');
    Route::get('/application-complete','VacanciesController@complete')->name('vacancy.complete');
    Route::get('applications','HomeController@applications')->name('applications');
    Route::get('interviews','HomeController@interviews')->name('interviews');
    Route::get('viewInterview','HomeController@viewInterview')->name('view-interview');
    Route::get('placements','HomeController@placements')->name('placements');
    Route::get('tests','TestController@index')->name('tests');
    Route::get('test/{test}','TestController@start')->name('tests.start');
    Route::post('test/{userTest}','TestController@processTest')->name('tests.process');
    Route::get('test-result/{userTest}','TestController@result')->name('tests.result');
    Route::get('test-results/{test}','TestController@results')->name('tests.results');

    Route::get('profile','ProfileController@profile')->name('profile');
    Route::post('update-profile','ProfileController@update')->name('save-profile');

    Route::get('image','HomeController@showImage')->name('image');
    Route::get('download','HomeController@download')->name('download');
    Route::get('candidate-remove-file/{fieldId}','HomeController@removeFile')->name('remove-file');

    Route::get('candidate-remove-picture','HomeController@removePicture')->name('remove-picture');
    Route::get('candidate-remove-cv','HomeController@removeCv')->name('remove-cv');




});

//general auth routes

app/EmployerFieldGroup.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class EmployerFieldGroup extends Model
{
    protected $fillable = ['name','sort_order','registration','public'];

    public function employerFields(){
        return $this->hasMany(EmployerField::class);
    }

}

app/Http/Controllers/Admin/EmployerFieldGroupsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests;

use App\EmployerFieldGroup;
use Illuminate\Http\Request;

class EmployerFieldGroupsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $keyword = $request->get('search');
        $perPage = 25;

        if (!empty($keyword)) {
            $employerfieldgroups = EmployerFieldGroup::latest()->paginate($perPage);
        } else {
            $employerfieldgroups = EmployerFieldGroup::latest()->paginate($perPage);
        }

        return view('admin.employer-field-groups.index', compact('employerfieldgroups'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('admin.employer-field-groups.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        
        $requestData = $request->all();
        
        EmployerFieldGroup::create($requestData);

        return redirect('admin/employer-field-groups')->with('flash_message', __('site.changes-saved'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function show($id)
    {
        $employerfieldgroup = EmployerFieldGroup::findOrFail($id);

        return view('admin.employer-field-groups.show', compact('employerfieldgroup'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     *
     * @return \Illuminate\View\View
     */
    public function edit($id)
    {
        $employerfieldgroup = EmployerFieldGroup::findOrFail($id);

        return view('admin.employer-field-groups.edit', compact('employerfieldgroup'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        
        $requestData = $request->all();
        
        $employerfieldgroup = EmployerFieldGroup::findOrFail($id);
        $employerfieldgroup->update($requestData);

        return redirect('admin/employer-field-groups')->with('flash_message', __('site.changes-saved'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     *
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy($id)
    {
        EmployerFieldGroup::destroy($id);

        return redirect('admin/employer-field-groups')->with('flash_message', __('site.record-deleted'));
    }
}

Resources/views/admin/employer-field-groups/create.blade.php
@extends('layouts.admin-page')

@section('pageTitle',__('site.employer-form'))
@section('page-title',__('site.create-new').' '.__('site.form-section'))

@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div  >
                    <div >
                        <a href="{{ url('/admin/employer-field-groups') }}" title="@lang('site.back')"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                        <br />
                        <br />


                        <form method="POST" action="{{ url('/admin/employer-field-groups') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('admin.employer-field-groups.form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@include('admin.partials.user-field-form-logic')

Resources/views/admin/employer-field-groups/edit.blade.php
@extends('layouts.admin-page')

@section('pageTitle',__('site.employer-form'))
@section('page-title',__('site.edit').' '.__('site.form-section').': '.$employerfieldgroup->name)

@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div  >
                    <div  >
                        <a href="{{ url('/admin/employer-field-groups') }}" title="@lang('site.back')"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                        <br />
                        <br />



                        <form method="POST" action="{{ url('/admin/employer-field-groups/' . $employerfieldgroup->id) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('admin.employer-field-groups.form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@include('admin.partials.user-field-form-logic')

Resources/views/admin/employer-field-groups/form.blade.php
<div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
    <label for="name" class="control-label">@lang('site.name')</label>
    <input class="form-control" name="name" type="text" id="name" value="{{ old('name',isset($employerfieldgroup->name) ? $employerfieldgroup->name : '') }}" >
    {!! clean( $errors->first('name', '<p class="help-block">:message</p>') ) !!}
</div>
<div class="form-group {{ $errors->has('sort_order') ? 'has-error' : ''}}">
    <label for="sort_order" class="control-label">@lang('site.sort-order')</label>
    <input class="form-control number" name="sort_order" type="text" id="sort_order" value="{{ old('sort_order',isset($employerfieldgroup->sort_order) ? $employerfieldgroup->sort_order : '') }}" >
    {!! clean( $errors->first('sort_order', '<p class="help-block">:message</p>') ) !!}
</div>

<div class="form-group {{ $errors->has('public') ? 'has-error' : ''}}">
    <label for="public" class="control-label">@lang('site.show-public')</label>
    <select name="public" class="form-control" id="public" >
        @foreach (json_decode('{"0":"'.__('site.no').'","1":"'.__('site.yes').'"}', true) as $optionKey => $optionValue)
            <option value="{{ $optionKey }}" {{ ((null !== old('public',@$candidatefieldgroup->public)) && old('public',@$candidatefieldgroup->public) == $optionKey) ? 'selected' : ''}}>{{ $optionValue }}</option>
        @endforeach
    </select>
    {!! clean( $errors->first('public', '<p class="help-block">:message</p>') ) !!}
</div>


<div id="option-box"  class="form-group {{ $errors->has('registration') ? 'has-error' : ''}}">
    <label for="registration" class="control-label">@lang('site.show-registration')</label>
    <select name="registration" class="form-control" id="registration" >
        @foreach (json_decode('{"0":"'.__('site.no').'","1":"'.__('site.yes').'"}', true) as $optionKey => $optionValue)
            <option value="{{ $optionKey }}" {{ ((null !== old('registration',@$employerfieldgroup->registration)) && old('registration',@$employerfieldgroup->registration) == $optionKey) ? 'selected' : ''}}>{{ $optionValue }}</option>
        @endforeach
    </select>
    {!! clean( $errors->first('registration', '<p class="help-block">:message</p>') ) !!}
</div>

<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? __('site.update') : __('site.create') }}">
</div>

Resources/views/admin/employer-field-groups/index.blade.php
@extends('layouts.admin-page-wide')


@section('pageTitle',__('site.employer-form'))
@section('page-title',__('site.form-sections'))

@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div >
                    <div  >
                        <a href="{{ url('/admin/employer-field-groups/create') }}" class="btn btn-success btn-sm" title="@lang('site.add-new')">
                            <i class="fa fa-plus" aria-hidden="true"></i> @lang('site.add-new')
                        </a>



                        <br/>
                        <br/>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>#</th><th>@lang('site.name')</th><th>@lang('site.sort-order')</th>
                                        <th>@lang('site.fields')</th>
                                        <th>@lang('site.registration')</th>
                                        <th>@lang('site.actions')</th>
                                    </tr>
                                </thead>
                                <tbody>
                                @foreach($employerfieldgroups as $item)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $item->name }}</td><td>{{ $item->sort_order }}</td>
                                        <td>{{ $item->employerFields()->count() }}</td>
                                        <td>{{ boolToString($item->registration) }}</td>
                                        <td>
                                            <a href="{{ route('admin.employer-fields.index',['employerFieldGroup'=>$item->id]) }}" title="@lang('site.manage-fields')"><button class="btn btn-success btn-sm"><i class="fa fa-file-invoice" aria-hidden="true"></i> @lang('site.manage-fields')</button></a>

                                            <a href="{{ url('/admin/employer-field-groups/' . $item->id) }}" title="@lang('site.view')"><button class="btn btn-info btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> @lang('site.view')</button></a>
                                            <a href="{{ url('/admin/employer-field-groups/' . $item->id . '/edit') }}" title="@lang('site.edit')"><button class="btn btn-primary btn-sm"><i class="fa fa-edit" aria-hidden="true"></i> @lang('site.edit')</button></a>

                                            <form method="POST" action="{{ url('/admin/employer-field-groups' . '/' . $item->id) }}" accept-charset="UTF-8" class="int_inlinedisp">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-danger btn-sm" title="@lang('site.delete')" onclick="return confirm(&quot;@lang('site.confirm-delete')&quot;)"><i class="fa fa-trash" aria-hidden="true"></i> @lang('site.delete')</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                            <div class="pagination-wrapper"> {!! clean( $employerfieldgroups->appends(['search' => Request::get('search')])->render() ) !!} </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

Resources/views/admin/employer-field-groups/show.blade.php
@extends('layouts.admin-page')

@section('pageTitle',__('site.employer-form'))
@section('page-title',__('site.form-section').': '.$employerfieldgroup->name)

@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div  >
                    <div  >

                        <a href="{{ url('/admin/employer-field-groups') }}" title="@lang('site.back')"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                        <a href="{{ url('/admin/employer-field-groups/' . $employerfieldgroup->id . '/edit') }}" ><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> @lang('site.edit')</button></a>

                        <form method="POST" action="{{ url('admin/employer-field-groups' . '/' . $employerfieldgroup->id) }}" accept-charset="UTF-8" class="int_inlinedisp">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-sm" title="@lang('site.delete')" onclick="return confirm(&quot;@lang('site.confirm-delete')?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> @lang('site.delete')</button>
                        </form>
                        <br/>
                        <br/>

                        <ul class="list-group">
                            <li class="list-group-item active">@lang('site.id')</li>
                            <li class="list-group-item">{{ $employerfieldgroup->id }}</li>
                            <li class="list-group-item active">@lang('site.name')</li>
                            <li class="list-group-item">{{ $employerfieldgroup->name }}</li>
                            <li class="list-group-item active">@lang('site.sort-order')</li>
                            <li class="list-group-item">{{ $employerfieldgroup->sort_order }}</li>


                            <li class="list-group-item active">@lang('site.show-public')</li>
                            <li class="list-group-item">{{ boolToString($employerfieldgroup->public) }}</li>

                            <li class="list-group-item active">@lang('site.show-registration')</li>
                            <li class="list-group-item">{{ boolToString($employerfieldgroup->registration) }}</li>


                        </ul>




                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection