routes/web.php
        Route::get('/contact','HomeController@contact')->name('contact');
        Route::post('/contact/send-mail','HomeController@sendMail')->name('contact.send-mail');
        Route::get('/blog','BlogController@index')->name('blog');
        Route::get('/blog/{blogPost}','BlogController@post')->name('blog.post');
    });

    Route::get('/profiles','ProfilesController@index')->name('profiles');
    Route::get('/profiles/{candidate}','ProfilesController@profile')->name('profile');
    Route::get('/shortlist-candidate/{candidate}','ProfilesController@shortlistCandidate')->name('shortlist-candidate');
    Route::get('/shortlist','ProfilesController@shortlist')->name('shortlist');
    Route::get('/shortlist/remove/{candidate}','ProfilesController@removeFromList')->name('shortlist.remove');

});

Route::get('/vacancies','Candidate\VacanciesController@index')->name('vacancies');
Route::get('/vacancies/{vacancy}','Candidate\VacanciesController@view')->name('view-vacancy');

Route::group(['namespace'=>'Employer','middleware'=>['employer']],function(){
    Route::get('order-forms','OrderController@forms')->name('order-forms');
    Route::get('/order-form/{orderForm}','OrderController@form')->name('order-form');
    Route::post('/order/save-form/{orderForm}','OrderController@save')->name('order.save-form');
    Route::get('/order-complete','OrderController@complete')->name('order.complete');
});




Route::get('test','TestController@index');

Route::get('register/employer','Auth\RegisterController@employer')->name('register.employer');
Route::get('register/candidate','Auth\RegisterController@candidate')->name('register.candidate');
Route::post('register/employer','Auth\RegisterController@registerEmployer')->name('register.save-employer');
Route::post('register/candidate','Auth\RegisterController@registerCandidate')->name('register.save-candidate');

Auth::routes();
Route::get('logout','Auth\LoginController@logout');
Route::get('social/login/{network}','Auth\LoginController@social')->name('social.login');
Route::get('social/employer','Auth\LoginController@completeEmployer')->name('social.employer');
Route::post('social/save-employer','Auth\LoginController@saveEmployer')->name('social.save-employer');
Route::get('social/candidate','Auth\LoginController@completeCandidate')->name('social.candidate');
Route::post('social/save-candidate','Auth\LoginController@saveCandidate')->name('social.save-candidate');

Route::get('email-confirmation','Auth\RegisterController@confirm')->name('register.confirm');
Route::get('confirm/employer/{hash}','Auth\RegisterController@confirmEmployer')->name('confirm.employer');
Route::get('confirm/candidate/{hash}','Auth\RegisterController@confirmCandidate')->name('confirm.candidate');

Route::get('home', 'HomeController@index')->name('home')->middleware('auth');
Route::get('pay/{hash}','Site\CartController@pay')->name('cart.pay');

Route::group(['middleware'=>['auth','admin',\App\Http\Middleware\UserLimit::class],'prefix' => 'admin', 'as' => 'admin.','namespace'=>'Admin'],function() {

    Route::get('/', 'HomeController@index')->name('dashboard');
    Route::get('users/search','HomeController@search')->name('users.search');
    Route::get('image','HomeController@showImage')->name('image');
    Route::get('download','HomeController@download')->name('download');


    Route::get('approve-invoice/{invoice}','InvoicesController@approve')->name('invoices.approve');
    Route::resource('invoices', 'InvoicesController');
    Route::get('delete-invoice/{id}','InvoicesController@destroy')->name('invoices.delete');
    Route::resource('invoice-categories', 'InvoiceCategoriesController');

    Route::resource('currencies', 'CurrenciesController');

    Route::resource('features', 'FeaturesController');

    Route::resource('article-categories', 'ArticleCategoriesController');

    Route::resource('articles', 'ArticlesController');
    Route::resource('help-posts', 'HelpPostsController');
    Route::resource('help-categories', 'HelpCategoriesController');
    Route::resource('blog-categories', 'BlogCategoriesController');
    Route::resource('blog-posts', 'BlogPostsController');

    Route::get('blog-remove-picture/{id}','BlogPostsController@removePicture')->name('blog.remove-picture');

    Route::get('candidate-remove-picture/{id}','CandidatesController@removePicture')->name('candidate.remove-picture');
    Route::get('candidate-remove-cv/{id}','CandidatesController@removeCv')->name('candidate.remove-cv');

    Route::get('candidate-remove-file/{fieldId}/{userId}','CandidatesController@removeFile')->name('candidate.remove-file');

    Route::get('candidate/download-profile/{id}/{full}','CandidatesController@download')->name('candidate.download');
    Route::get('candidates/search','CandidatesController@search')->name('candidates.search');
    Route::get('candidates/export','CandidatesController@export')->name('candidates.export');
    Route::get('candidates/import-1','CandidatesController@importForm')->name('candidates.import-1');
    Route::post('candidates/import-1','CandidatesController@importUpload')->name('candidates.import-upload');
    Route::get('candidates/import-2','CandidatesController@importFields')->name('candidates.import-2');
    Route::post('candidates/import-2','CandidatesController@saveImportFields')->name('candidates.import-save-fields');
    Route::get('candidates/import-3','CandidatesController@importPreview')->name('candidates.import-preview');
    Route::post('candidates/process-import','CandidatesController@processImport')->name('candidates.import-process');
    Route::get('candidates/import-4','CandidatesController@completeImport')->name('candidates.import-complete');
    Route::get('candidates/test-results/{user}','CandidatesController@tests')->name('candidates.tests');
    Route::resource('candidates', 'CandidatesController');
    Route::resource('categories', 'CategoriesController');

    Route::resource('notes','NotesController');
    Route::get('user-notes/{user}','NotesController@index')->name('notes.index');
    Route::get('user-notes/create/{user}','NotesController@create')->name('notes.create');
    Route::post('user-notes/{user}','NotesController@store')->name('notes.store');

    Route::resource('attachments', 'AttachmentsController');
    Route::get('user-attachments/{user}','AttachmentsController@index')->name('attachments.index');
    Route::get('user-attachments/create/{user}','AttachmentsController@create')->name('attachments.create');
    Route::post('user-attachments/{user}','AttachmentsController@store')->name('attachments.store');

    Route::get('employer-remove-file/{fieldId}/{userId}','EmployersController@removeFile')->name('employer.remove-file');
    Route::get('employers/search','EmployersController@search')->name('employers.search');
    Route::get('employers/export','EmployersController@export')->name('employers.export');
    Route::get('employers/import-1','EmployersController@importForm')->name('employers.import-1');
    Route::post('employers/import-1','EmployersController@importUpload')->name('employers.import-upload');
    Route::get('employers/import-2','EmployersController@importFields')->name('employers.import-2');
    Route::post('employers/import-2','EmployersController@saveImportFields')->name('employers.import-save-fields');
    Route::get('employers/import-3','EmployersController@importPreview')->name('employers.import-preview');
    Route::post('employers/process-import','EmployersController@processImport')->name('employers.import-process');
    Route::get('employers/import-4','EmployersController@completeImport')->name('employers.import-complete');
    Route::resource('employers', 'EmployersController');

    Route::resource('employments', 'EmploymentsController');
    Route::get('employment-records/{user}','EmploymentsController@index')->name('employments.index');
    Route::get('employment-records/create/{user}','EmploymentsController@create')->name('employments.create');
    Route::post('employment-records/{user}','EmploymentsController@store')->name('employments.store');
    Route::get('browse-employments','EmploymentsController@browse')->name('employments.browse');

    Route::get('create-employment','EmploymentsController@createEmployment')->name('employments.create-employment');
    Route::post('store-employment','EmploymentsController@storeEmployment')->name('employments.store-employment');

    Route::resource('employment-comments', 'EmploymentCommentsController');
    Route::get('employment-comment/{employment}','EmploymentCommentsController@index')->name('employment-comments.index');
    Route::get('employment-comment/create/{employment}','EmploymentCommentsController@create')->name('employment-comments.create');
    Route::post('employment-comment/{employment}','EmploymentCommentsController@store')->name('employment-comments.store');

    Route::post('employment-comment/upload-attachment/{id}','EmploymentCommentsController@upload')->name('employment-comments.upload');
    Route::post('employment-comment/remove-upload/{id}','EmploymentCommentsController@removeUpload')->name('employment-comments.remove-upload');
    Route::get('employment-comment/download-attachment/{employmentCommentAttachment}','EmploymentCommentsController@downloadAttachment')->name('employment-comments.download-attachment');
    Route::get('employment-comment/download-attachments/{employmentComment}','EmploymentCommentsController@downloadAttachments')->name('employment-comments.download-attachments');

    Route::get('employment-comment/delete-attachment/{employmentCommentAttachment}','EmploymentCommentsController@deleteAttachment')->name('employment-comments.delete-attachment');


    Route::resource('orders', 'OrdersController');
    Route::post('create-order','OrdersController@doCreate')->name('orders.do-create');
    Route::get('orders/create/{orderForm}','OrdersController@create')->name('orders.create');

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $fillable = ['user_id','amount','payment_method_id','title','description','paid','due_date','invoice_category_id','hash'];

    public function paymentMethod(){
        return $this->belongsTo(PaymentMethod::class);
    }


    public function user(){
        return $this->belongsTo(User::class);
    }

    public function invoiceCategory(){
        return $this->belongsTo(InvoiceCategory::class);
    }

    public function orders(){
        return $this->belongsToMany(Order::class);
    }
}

app/Http/Controllers/Account/InvoiceController.php
<?php

namespace App\Http\Controllers\Account;


use App\Invoice;
use App\Lib\HelperTrait;
use App\Lib\PaymentMethods;
use App\PaymentMethod;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

class InvoiceController extends Controller
{
    use HelperTrait;
    public function __construct(){
       // $this->middleware('auth');
    }

    public function index(){
        $invoices = Auth::user()->invoices()->orderBy('id','desc')
                    ->paginate(30);

        return view('account.billing.invoices',[
            'invoices'=>$invoices
        ]);
    }

    public function view(Invoice $invoice){

        $this->authorize('view',$invoice);

        $address = $this->billingAddress();
        return view('account.billing.view-invoice',[
           'invoice'=>$invoice,
            'address'=>$address
        ]);
    }

    public function pay(Invoice $invoice){
        session(['invoice'=>$invoice->id]);
        return redirect()->route('user.invoice.cart');
    }

    public function cart(Request $request){

        $invoiceId = session()->get('invoice');
        $invoice = Invoice::find($invoiceId);

        if($invoice->paid == 1){
            session()->forget('invoice');
            return redirect()->route('user.billing.invoices');
        }

        $description = $invoice->title;

        $paymentMethods = [];


        //get global methods
        foreach(PaymentMethod::where('status',1)->orderBy('sort_order')->get() as $method){
            if (is_dir(PAYMENT_PATH.'/'.$method->code)){
                $paymentMethods[$method->id] = $method;
            }

        }


        return view('account.billing.cart',['invoice'=>$invoice,'description'=>$description,'paymentMethods'=>$paymentMethods]);
    }

    public function cancel(Request $request)
    {
        session()->forget('invoice');
        $this->successMessage(__('site.removed-cart'));
        return redirect()->route('home');
    }

    public function checkout(Request $request){

        //check if user has any billing address
        $user = Auth::user();
        $address = $this->billingAddress();
        $invoiceId = session()->get('invoice');
        $invoice = Invoice::find($invoiceId);

        if($invoice->paid == 1){
            session()->forget('invoice');
            return redirect()->route('user.billing.invoices');
        }



        //check if it is a free invoice
        if($invoice->amount== 0){
            $result = __('site.order-success');
            session()->forget('invoice');

            $this->approveInvoice($invoice);
            $this->successMessage($result);
            return redirect()->route('user.billing.invoices');
        }


        $description = $invoice->title;
        $output= [];
        $output['address']=$address;
        $output['description']=$description;
        $output['user'] = $user;
        $output['item'] = $description;
        $output['invoice'] = $invoice;
        $output['paymentMethod'] = $invoice->paymentMethod->name;

        $code = $invoice->paymentMethod->code;
        $output['code'] = $code;

        //include function file
        if(!$this->setFunctions()){
            flashMessage(__lang('invalid-gateway'));
            return redirect()->route('user.invoice.cart');
        }

        if (!function_exists('carepro_pay')){
            flashMessage(__lang('invalid-gateway'));
            return redirect()->route('user.invoice.cart');
        }

        return carepro_pay($output);



/*        if(method_exists($paymentMethods,$code)){

           return call_user_func(array($paymentMethods, $code));

        }
        else{
            $view = 'account.methods.'.$invoice->paymentMethod->code;

            return view($view,$output);
        }*/



    }

    public function selectAddress(){
        $addresses = Auth::user()->billingAddresses;

        return view('account.billing.select-address',['addresses'=>$addresses]);
    }

    public function setAddress($id){
        session()->put('billing_address',$id);
        return redirect()->route('user.invoice.checkout');
    }

    public function complete(){
        $user = Auth::user();

        session()->forget('invoice');

        return view('account.billing.complete');
    }

    public function setMethod(Request $request){
        $this->validate($request,[
            'method'=>'required|integer'
        ]);
        $requestData = $request->all();
        $invoiceId = session()->get('invoice');
        $invoice = Invoice::find($invoiceId);
        $invoice->payment_method_id = $requestData['method'];
        $invoice->save();
        return redirect()->route('user.invoice.checkout');
    }


    private function setFunctions($code=null){
        if (!$code){
            $invoiceId = session()->get('invoice');
            $invoice = Invoice::find($invoiceId);
            $code = $invoice->paymentMethod->code;
        }

        $file = 'gateways/payment/'.$code.'/functions.php';
        if (file_exists($file)){
            require_once($file);
            return true;
        }
        else{
            return false;
        }
    }

    public function ipn(Request $request,$code){
        $this->setFunctions($code);
        if (!function_exists('carepro_ipn')){
            flashMessage(__lang('invalid-gateway'));
            return redirect()->route('user.invoice.cart');
        }
        return carepro_ipn();
    }

    public function method(Request $request,$code,$function){
        $this->setFunctions($code);
        if (!function_exists($function)){
            flashMessage(__lang('invalid-gateway'));
            return redirect()->route('user.invoice.cart');
        }
        return $function();
    }

}

app/Http/Controllers/Api/Account/InvoiceController.php
<?php

namespace App\Http\Controllers\Api\Account;

use App\Http\Controllers\Controller;
use App\Http\Resources\BillingAddressResource;
use App\Http\Resources\InvoiceCategoryResource;
use App\Http\Resources\InvoiceResource;
use App\Http\Resources\PaymentMethodResource;
use App\Invoice;
use App\InvoiceCategory;
use App\Lib\HelperTrait;
use App\PaymentMethod;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class InvoiceController extends Controller
{
    use HelperTrait;

    public function index(Request $request){
        $invoices = $request->user()->invoices()->orderBy('id','desc')
            ->paginate(30);

        return InvoiceResource::collection($invoices);

    }

    public function view(Invoice $invoice){

        $this->authorize('view',$invoice);

        return new InvoiceResource($invoice);

    }

    public function invoiceCategories(){
        $invoiceCategories = InvoiceCategory::orderBy('sort_order')->get();
        return InvoiceCategoryResource::collection($invoiceCategories);
    }

    public function create(Request $request){

    }


}

Resources/views/admin/invoices/create.blade.php
@extends('layouts.admin-page')

@section('pageTitle',__('site.create-new').' '.__('site.invoice'))
@section('page-title',__('site.create-new').' '.__('site.invoice'))

@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div  >
                    <div >
                        <a href="{{ url('/admin/invoices') }}" title="@lang('site.back')"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                        <br />
                        <br />


                        <form method="POST" action="{{ url('/admin/invoices') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('admin.invoices.form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@include('admin.invoices.form-logic')

Resources/views/admin/invoices/edit.blade.php
@extends('layouts.admin-page')

@section('pageTitle',__('site.edit').' '.__('site.invoice').' #'.$invoice->id)
@section('page-title',__('site.edit').' '.__('site.invoice').' #'.$invoice->id)

@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div  >
                    <div  >
                        <a href="{{ url('/admin/invoices') }}" title="@lang('site.back')"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                        <br />
                        <br />



                        <form method="POST" action="{{ url('/admin/invoices/' . $invoice->id) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('admin.invoices.form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@include('admin.invoices.form-logic')

Resources/views/admin/invoices/form-logic.blade.php
@section('header')
    <link href="{{ asset('vendor/pickadate/themes/default.date.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/pickadate/themes/default.time.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/pickadate/themes/default.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('vendor/select2/css/select2.min.css') }}">

@endsection


@section('footer')
    <script src="{{ asset('vendor/pickadate/picker.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/pickadate/picker.date.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/pickadate/picker.time.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/pickadate/legacy.js') }}" type="text/javascript"></script>
    <script src="{{ asset('vendor/select2/js/select2.min.js') }}"></script>

    <script  type="text/javascript">
"use strict";

        $('#user_id').select2({
            placeholder: "@lang('site.search-users')...",
            minimumInputLength: 3,
            ajax: {
                url: '{{ route('admin.users.search') }}',
                dataType: 'json',
                data: function (params) {
                    return {
                        term: $.trim(params.term)
                    };
                },
                processResults: function (data) {
                    return {
                        results: data
                    };
                },
                cache: true
            }

        });

        $('.date').pickadate({
            format: 'yyyy-mm-dd'
        });


    </script>
@endsection

Resources/views/admin/invoices/form.blade.php
{{-- <div class="form-group {{ $errors->has('user_id') ? 'has-error' : ''}}">
    <label for="user_id" class="control-label required">@lang('site.user')</label>

    <select required  name="user_id" id="user_id" class="form-control">
        @php
        $userId = old('user_id',isset($invoice->user_id) ? $invoice->user_id : '');
        @endphp

        @if($userId)
            <option selected value="{{ $userId }}">{{ \App\User::find($userId)->name }} ({{ \App\User::find($userId)->email }}) </option>
        @endif
    </select>

    {!! clean( check( $errors->first('user_id', '<p class="help-block">:message</p>')) ) !!}
</div>
 --}}
<div class="form-group {{ $errors->has('user_id') ? 'has-error' : ''}}">
    <label for="user_id" class="control-label">@lang('Employee/Customer')</label>

    <select required  name="user_id" id="user_id" class="form-control">
        <?php
        $userId = old('user_id',isset($employment->candidate->user->id) ? $employment->candidate->user->id : false);
        ?>
        @if($userId)
            <option selected value="{{ $userId }}">{{ \App\User::find($userId)->name }} &lt;{{ \App\User::find($userId)->email }}&gt; </option>
        @endif
    </select>

    {!! clean( $errors->first('user_id', '<p class="help-block">:message</p>') ) !!}
</div>


<div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
    <label for="title" class="control-label required">@lang('site.title')</label>
    <input required class="form-control" name="title" type="text" id="title" value="{{ old('title',isset($invoice->title) ? $invoice->title : '') }}" >
    {!! clean( check( $errors->first('title', '<p class="help-block">:message</p>')) ) !!}
</div>


<div class="form-group {{ $errors->has('description') ? 'has-error' : ''}}">
    <label for="description" class="control-label">@lang('site.description')</label>
     <textarea class="form-control" name="description" id="description" >{{ old('description',isset($invoice->description) ? $invoice->description : '') }}</textarea>
    {!! clean( check( $errors->first('description', '<p class="help-block">:message</p>')) ) !!}
</div>



<div class="form-group {{ $errors->has('amount') ? 'has-error' : ''}}">
    <label for="amount" class="control-label required">@lang('site.amount')</label>
    <input required class="form-control digit" name="amount" type="text" id="amount" value="{{ old('amount',isset($invoice->amount) ? $invoice->amount : '') }}" >
    {!! clean( check( $errors->first('amount', '<p class="help-block">:message</p>')) ) !!}
</div>




<div class="form-group {{ $errors->has('paid') ? 'has-error' : ''}}">
    <label for="paid" class="control-label required">@lang('site.paid')</label>
    <select required name="paid" class="form-control" id="paid" >
    @foreach (json_decode('{"0":"No","1":"Yes"}', true) as $optionKey => $optionValue)
        <option value="{{ $optionKey }}" {{ ((null !== old('paid',@$invoice->paid)) && old('invoice',@$invoice->paid) == $optionKey) ? 'selected' : ''}}>{{ $optionValue }}</option>
    @endforeach
</select>
    {!! clean( check( $errors->first('paid', '<p class="help-block">:message</p>')) ) !!}
</div>

<div class="form-group {{ $errors->has('payment_method_id') ? 'has-error' : ''}}">
    <label for="payment_method_id" class="control-label">@lang('site.payment-method')</label>
    <select  class="form-control" name="payment_method_id" id="payment_method_id">
        <option value=""></option>
        @foreach(\App\PaymentMethod::get() as $paymentMethod)
            <option @if(old('payment_method_id',isset($invoice->payment_method_id) ? $invoice->payment_method_id : '')==$paymentMethod->id) selected @endif value="{{ $paymentMethod->id }}">{{ $paymentMethod->name }}</option>
        @endforeach
    </select>

    {!! clean( check( $errors->first('payment_method_id', '<p class="help-block">:message</p>')) ) !!}
</div>



<div class="form-group {{ $errors->has('due_date') ? 'has-error' : ''}}">
    <label for="due_date" class="control-label required">@lang('site.due-date')</label>
    <input required class="form-control date" name="due_date" type="text" id="due_date" value="{{ old('due_date',isset($invoice->due_date) ? $invoice->due_date : \Illuminate\Support\Carbon::now()->toDateString()) }}" >
    {!! clean( check( $errors->first('due_date', '<p class="help-block">:message</p>')) ) !!}
</div>

<div class="form-group {{ $errors->has('invoice_category_id') ? 'has-error' : ''}}">
    <label for="invoice_category_id" class="control-label">@lang('site.invoice-category')</label>
    <select  class="form-control" name="invoice_category_id" id="invoice_category_id">
        <option value=""></option>
        @foreach(\App\InvoiceCategory::get() as $invoiceCategory)
            <option @if(old('invoice_category_id',isset($invoice->invoice_category_id) ? $invoice->invoice_category_id : '')==$invoiceCategory->id) selected @endif value="{{ $invoiceCategory->id }}">{{ $invoiceCategory->name }}</option>
        @endforeach
    </select>

    {!! clean( check( $errors->first('invoice_category_id', '<p class="help-block">:message</p>')) ) !!}
</div>

@if($formMode=='create')
    <div class="row">
        <div class="col-md-6">
            <div class="form-check">
                <input class="form-check-input" checked  type="checkbox" value="1" id="notify" name="notify">
                <label class="form-check-label" for="notify">
                    @lang('site.notify-user')
                </label>
            </div>
        </div>
    </div>
    <br/>
@endif

<div class="form-group">
    <input class="btn btn-primary" type="submit" value="{{ $formMode === 'edit' ? __('site.update') : __('site.create') }}">
</div>

Resources/views/admin/invoices/show.blade.php
@extends('layouts.admin-page')

@section('pageTitle',__('site.invoice').' #'.$invoice->id)
@section('page-title',__('site.invoice').' #'.$invoice->id)

@section('page-content')
    <div class="container-fluid">
        <div class="row">


            <div class="col-md-12">
                <div  >
                    <div  >

                        @can('access','view_invoices')
                        <a href="{{ url('/admin/invoices') }}"><button class="btn btn-warning btn-sm"><i class="fa fa-arrow-left" aria-hidden="true"></i> @lang('site.back')</button></a>
                       @endcan
                       @can('access','edit_invoice')
                        <a href="{{ url('/admin/invoices/' . $invoice->id . '/edit') }}" ><button class="btn btn-primary btn-sm"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> @lang('site.edit')</button></a>
                        @endcan

                        @can('access','delete_invoice')
                        <form method="POST" action="{{ url('admin/invoices' . '/' . $invoice->id) }}" accept-charset="UTF-8" class="int_inlinedisp">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <button type="submit" class="btn btn-danger btn-sm" title="@lang('site.delete')" onclick="return confirm(&quot;@lang('site.confirm-delete')?&quot;)"><i class="fa fa-trash-o" aria-hidden="true"></i> @lang('site.delete')</button>
                        </form>
                        @endcan
                        <br/>
                        <br/>


                        <ul class="list-group">
                            <li class="list-group-item active">@lang('site.id')</li>
                            <li class="list-group-item">#{{ $invoice->id }}</li>
                            <li class="list-group-item active">@lang('site.user')</li>
                            <li class="list-group-item"><a @if($invoice->user->role_id==2) href="{{ url('/admin/employers/' . $invoice->user_id) }}" @elseif($invoice->user->role_id==3)  href="{{ url('/admin/candidates/' . $invoice->user_id) }}" @endif >{{ $invoice->user->name }} ({{ roleName($invoice->user->role_id) }})</a></li>
                            <li class="list-group-item active">@lang('site.amount')</li>
                            <li class="list-group-item">{{ price($invoice->amount,$invoice->currency_id) }}</li>
                            <li class="list-group-item active">@lang('site.item')</li>
                            <li class="list-group-item">{{ $invoice->title }}</li>
                            <li class="list-group-item active">@lang('site.description')</li>
                            <li class="list-group-item">{!! clean( check(nl2br($invoice->description)) ) !!}</li>
                            <li class="list-group-item active">@lang('site.status')</li>
                            <li class="list-group-item">{{ ($invoice->paid==1)? __('site.paid'):__('site.unpaid') }}</li>
                            @if($invoice->paymentMethod()->exists())

                            <li class="list-group-item active">@lang('site.payment-method')</li>
                            <li class="list-group-item">{{ $invoice->paymentMethod->name }}</li>
                            @endif

                            <li class="list-group-item active">@lang('site.added-on')</li>
                            <li class="list-group-item">{{ \Illuminate\Support\Carbon::parse($invoice->created_at)->format('d/M/Y') }}</li>
                            <li class="list-group-item active">@lang('site.due-date')</li>
                            <li class="list-group-item">{{ \Illuminate\Support\Carbon::parse($invoice->due_date)->format('d/M/Y') }}</li>
                            <li class="list-group-item active">@lang('site.category')</li>
                            <li class="list-group-item">@if($invoice->invoiceCategory()->exists())
                                    {{ $invoice->invoiceCategory->name }}
                                @endif</li>

                        </ul>



                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection